In [1]:
import pandas as pd
from sklearn.metrics import cohen_kappa_score

In [2]:
df_rendika = pd.read_csv('data/processed/preprocessed_dataset_rendika.csv')
df_faldy = pd.read_csv('data/processed/preprocessed_dataset_fadly.csv')

In [3]:
df_rendika

,clean_text,Label,char_len,word_count
0,nyata bestienya koruptor kakap pertamina riva ...,0,244,38
1,salah satu lebih pertamax oplos rubah suara kn...,0,70,10
2,juga win,1,12,3
3,td pagi buka tiktok yang lucu sekarang konoha ...,0,130,22
4,herman khaeron amplop pertamina oplos,0,43,6
...,...,...,...,...
33680,update klaseman liga korupsi indonesia pt pert...,0,250,37
33681,tidak takut korupsi skr bukan m lg rtsan t mkn...,0,189,36
33682,info pente klaseman liga korupsi indonesia lki,1,56,8
33683,klaseman korupsi edar revisi arti kasus posisi...,0,85,12
33684,sampai akhir tahun klasemen tidak ubah geser s...,0,274,43

In [4]:
df_faldy

,clean_text,label,char_len,word_count
0,nyata bestienya koruptor kakap pertamina riva ...,0.0,244,38
1,salah satu lebih pertamax oplos rubah suara kn...,2.0,70,10
2,juga win,1.0,12,3
3,td pagi buka tiktok yang lucu sekarang konoha ...,0.0,130,22
4,herman khaeron amplop pertamina oplos,0.0,43,6
...,...,...,...,...
33680,update klaseman liga korupsi indonesia pt pert...,0.0,250,37
33681,tidak takut korupsi skr bukan m lg rtsan t mkn...,0.0,189,36
33682,info pente klaseman liga korupsi indonesia lki,0.0,56,8
33683,klaseman korupsi edar revisi arti kasus posisi...,0.0,85,12
33684,sampai akhir tahun klasemen tidak ubah geser s...,0.0,274,43

In [5]:
# merge berdasarkan clean_text untuk hitung agreement

df_agreement = pd.merge(
    df_rendika[['clean_text', 'Label']].rename(columns={'Label':'label_rendika'}),
    df_faldy[['clean_text', 'label']].rename(columns={'label':'label_rendika'}),
    on='clean_text', how='inner'
)

df_agreement.to_csv('data_merge_rendika_fadly.csv',index=False)

In [6]:
df_agreement

,clean_text,label_rendika_x,label_rendika_y
0,nyata bestienya koruptor kakap pertamina riva ...,0,0.0
1,salah satu lebih pertamax oplos rubah suara kn...,0,2.0
2,juga win,1,1.0
3,td pagi buka tiktok yang lucu sekarang konoha ...,0,0.0
4,herman khaeron amplop pertamina oplos,0,0.0
...,...,...,...
33680,update klaseman liga korupsi indonesia pt pert...,0,0.0
33681,tidak takut korupsi skr bukan m lg rtsan t mkn...,0,0.0
33682,info pente klaseman liga korupsi indonesia lki,1,0.0
33683,klaseman korupsi edar revisi arti kasus posisi...,0,0.0
33684,sampai akhir tahun klasemen tidak ubah geser s...,0,0.0

In [7]:
agreement_rate = (df_agreement['label_rendika_x']==df_agreement['label_rendika_y']).mean()

kappa_score = cohen_kappa_score(df_agreement['label_rendika_x'], df_agreement['label_rendika_y'])

print(f"Jumlah data yang bisa dibandingkan: {len(df_agreement)}")
print(f"Agreement Rate: {agreement_rate:.4f} ({agreement_rate*100:2f}%)")
print(f"Cohen's Kappa: {kappa_score:.4f}")

Jumlah data yang bisa dibandingkan: 33685
Agreement Rate: 0.6981 (69.805551%)
Cohen's Kappa: 0.2350